language: python
python:

  - "2.7"

# command to install dependencies
install:
  - pip install -r training_requirements.txt
  - pip install coveralls
  - pip install codecov

script:

  - coverage run --omit=*.virtualenvs*,*virtualenv* code/training_evaluation/train.py test

after_success:
  - coveralls
  - codecov

sudo: enabled
dist: trusty
